# Generated by Django 4.1.6 on 2023-02-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discoverHome", "0002_rename_participant_userinfo"),
    ]

    operations = []
