# Generated by Django 4.1.6 on 2023-02-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discoverHome", "0004_auto_20230211_0555"),
    ]

    operations = []
